# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: true
          cache-dependency-path: '**/go.sum'

      - name: Display Go version
        run: go version

      - name: Ensure dependencies
        run: |
          go mod tidy
          go mod download

      - name: Build project
        run: go build ./...

      - name: Run tests
        run: go test ./...

      - name: Start main.go and check port 5000
        run: |
          nohup go run main.go > server.log 2>&1 &
          sleep 5
          curl --fail http://localhost:5000 || (echo "Server failed to respond on port 5000" && exit 1)

